---
- name: cluster | Make sure RabbitMQ server is up
  service:
    name: rabbitmq-server
    state: started

- name: cluster | Make sure RabbitMQ app is up
  command: rabbitmqctl start_app

- name: cluster | Check if already in cluster
  command: rabbitmqctl cluster_status
  register: cluster_status
  changed_when: false

- include_tasks: join_cluster.yml
  when: ansible_hostname != rabbitmq_cluster_leader
