---
- name: create_users | Creating RabbitMQ single users
  rabbitmq_user:
    name: "{{ item['name'] }}"
    password: "{{ item['password'] }}"
    vhost: "{{ item['vhost'] }}"
    configure_priv: "{{ item['configure_priv'] }}"
    read_priv: "{{ item['read_priv'] }}"
    write_priv: "{{ item['write_priv'] }}"
    tags: "{{ item['tags'] }}"
    state: "{{ item['state'] }}"
  become: true
  no_log: true
  with_items: "{{ rabbitmq_users }}"
  when:
    - not rabbitmq_cluster | bool
    - rabbitmq_users is defined

- name: create_users | Remove RabbitMQ default user
  rabbitmq_user:
    user: guest
    state: absent
  become: true
  when:
    - not rabbitmq_cluster | bool

- name: create_users | Creating RabbitMQ cluster users
  rabbitmq_user:
    name: "{{ item['name'] }}"
    password: "{{ item['password'] }}"
    vhost: "{{ item['vhost'] }}"
    configure_priv: "{{ item['configure_priv'] }}"
    read_priv: "{{ item['read_priv'] }}"
    write_priv: "{{ item['write_priv'] }}"
    tags: "{{ item['tags'] }}"
    state: "{{ item['state'] }}"
  become: true
  no_log: true
  run_once: true
  with_items: "{{ rabbitmq_users }}"
  when:
    - rabbitmq_cluster | bool
    - rabbitmq_users is defined

- name: create_users | Remove RabbitMQ default user
  rabbitmq_user:
    user: guest
    state: absent
  become: true
  run_once: true
  when:
    - rabbitmq_cluster | bool
