---
- name: Add RabbitMQ Admin User
  rabbitmq_user:
    user: "{{ rabbitmq_admin_user }}"
    password: "{{ rabbitmq_admin_password }}"
    tags: administrator
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: Remove RabbitMQ default user
  rabbitmq_user:
    user: guest
    state: absent
