---
- name: enable_ha_queues | Set ha-mode to all nodes for all queues
  rabbitmq_policy:
    name: "ha-{{ rabbitmq_cluster_ha_strategy }}"
    tags:
      ha-mode: "{{ rabbitmq_cluster_ha_strategy }}"
      ha-sync-batch-size: "{{rabbitmq_cluster_ha_batch}}"
      ha-promote-on-failure: always
      ha-promote-on-shutdown: when-synced
      ha-sync-mode: automatic
    pattern: ".*"
    priority: 0
    state: present
    apply_to: all
  when:
    - rabbitmq_cluster_ha_strategy is defined
    - rabbitmq_cluster_ha_strategy == 'all'
  
- name: enable_ha_queues | Set ha-mode to exactly nodes for all queues
  rabbitmq_policy:
    name: "ha-{{ rabbitmq_cluster_ha_strategy }}"
    tags:
      ha-mode: "{{ rabbitmq_cluster_ha_strategy }}"
      ha-params: "{{ rabbitmq_cluster_ha_params }}"
      ha-sync-batch-size: "{{rabbitmq_cluster_ha_batch}}"
      ha-promote-on-failure: always
      ha-promote-on-shutdown: when-synced
      ha-sync-mode: automatic
    pattern: ".*"
    priority: 0
    state: present
    apply_to: all
  when:
    - rabbitmq_cluster_ha_strategy is defined
    - rabbitmq_cluster_ha_strategy != 'all'