---
- name: enable_ha_queues | Check if ha-mode is already enabled
  command: rabbitmqctl list_policies
  register: list_policies
  changed_when: false

- name: enable_ha_queues | Set ha-mode to exactly two nodes for all queues for backup
  command: rabbitmqctl set_policy ha-exactly-two ".*" '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'
  register: res
  failed_when: res.rc != 0
  when: list_policies.stdout.find("ha-exactly-two") == -1
