---
# Configure RabbitMQ for cluster
- name: erlang_cookie | Update Erlang cookie
  template:
    src: erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
    backup: yes
  notify: stop rabbitmq-server

- meta: flush_handlers
