---
# Configure RabbitMQ for cluster
- name: erlang_cookie | Backup old Erlang cookie
  command: cp -a /var/lib/rabbitmq/.erlang.cookie /var/lib/rabbitmq/.erlang.cookie.old
  changed_when: false

- name: erlang_cookie | Update Erlang cookie
  template:
    src: erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
  notify: stop rabbitmq-server

- meta: flush_handlers

- name: erlang_cookie | Remove old Erlang cookie
  file:
    path: /var/lib/rabbitmq/.erlang.cookie.old
    state: absent
  changed_when: false
