---
# Configure RabbitMQ for cluster
- name: erlang_cookie | Update Erlang cookie
  copy:
    content: "{{ rabbitmq_erlang_cookie }}"
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
    force: true
    backup: true
  notify: stop rabbitmq-server

- meta: flush_handlers
