---

# - name: Set IP addresses for all RabbitMQ instances
#   set_fact:
#     rabbitmq_ip: "{{ hostvars[item].internal_ip | default(hostvars[item].ansible_default_ipv4.address) }}"
#     cacheable: no
#   when:
#     - hostvars[item].rabbitmq_ip is undefined
#     - hostvars[item].ansible_hostname == ansible_hostname
#   with_items: "{{ groups[rabbitmq_hosts] }}"

- name: Add IP addresses of all RabbitMQ instances to "/etc/hosts" file
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ hostvars[item].ansible_hostname }}$"
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].ansible_hostname }}"
    state: present
  when:
    # - hostvars[item].rabbitmq_ip is defined
    - hostvars[item].ansible_hostname != ansible_hostname
  with_items: "{{ groups[rabbitmq_hosts] }}"
