---
- name: Update all packages
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: true

- name: Verify Python is installed
  apt: pkg=python-software-properties state=present

- name: Add RabbitMQ offical repo
  apt_repository:
    repo: deb https://dl.bintray.com/rabbitmq/debian xenial main
    state: present
    filename: rabbitmq

- name: Install RabbitMQ public key
  apt_key:
    url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
    state: present

- name: Add Erlang official repo
  apt_repository:
    repo: deb http://binaries.erlang-solutions.com/debian xenial contrib
    state: present
    filename: erlang

- name: Install Erlang public key
  apt_key:
    url: http://binaries.erlang-solutions.com/debian/erlang_solutions.asc
    state: present

- name: Install RabbitMQ & Erlang packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    install_recommends: yes
    state: present
  with_items:
    - rabbitmq-server
    - erlang-ssl
