---

- name: install | Erlang packages
  apt:
    name: "{{ erlang_packages }}"
    state: present
    force: true
    force_apt_get: true
    dpkg_options: "{{ dpkg_force_overwrite_configs | ternary('force-confdef,force-confnew', 'force-confdef,force-confold') }}"
    update_cache: true
    cache_valid_time: "{{ apt_cache_timeout | d(3600) }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
    RUNLEVEL: 1

- name: install | RabbitMQ packages
  apt:
    name: "{{ rabbitmq_packages }}"
    state: present
    force: true
    force_apt_get: true
    dpkg_options: "{{ dpkg_force_overwrite_configs | ternary('force-confdef,force-confnew', 'force-confdef,force-confold') }}"
    update_cache: true
    cache_valid_time: "{{ apt_cache_timeout | d(3600) }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
    RUNLEVEL: 1
