---

- name: Stop RabbitMQ app
  command: rabbitmqctl stop_app

- name: Add current node to cluster
  command: "rabbitmqctl join_cluster rabbit@{{ rabbitmq_cluster_master }}"

- name: Start RabbitMQ app
  command: rabbitmqctl start_app
