---
- name: cluster | join_cluster | Stop rabbitmq app
  shell: |
    rabbitmqctl stop_app

- name: cluster | join_cluster | Add this node to cluster
  shell: |
    rabbitmqctl join_cluster rabbit@{{ rabbitmq_cluster_leader }}

- name: cluster | join_cluster | Start rabbitmq app
  shell: |
    rabbitmqctl start_app
