---
# Copy cacert, cert and key file for TLS/SSL
- name: tls | Make sure TLS/SSL certificates exists
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: rabbitmq
    mode: 0644
  with_items:
    - { src: "{{ rabbitmq_cacertfile }}", dest: "{{ rabbitmq_cacertfile_dest }}" }
    - { src: "{{ rabbitmq_certfile }}", dest: "{{ rabbitmq_certfile_dest }}" }
    - { src: "{{ rabbitmq_keyfile }}", dest: "{{ rabbitmq_keyfile_dest }}" }
